name: PR Labeler
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
    - name: Labeler Action
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
