name: Mark stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Mark stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity.'
          stale-issue-label: 'stale-issue'
          exempt-issue-labels: 'enhancement,documentation,good-first-issue,question'
          stale-pr-label: 'stale-pr'
          exempt-pr-labels: 'work-in-progress'
          days-before-stale: 30
          days-before-close: -1
